### ISSUE TITLE
Command block interpreter interfering with commands that include "@" player selectors

### ISSUE THREAD

**Issue by tmad40blue** [wacossusca34/Consoles#26] opened 2015-10-23 01:31 UTC
Hi Jarcode, we talked on IRC and on my test server earlier. Just reporting the issue with command blocks.

This error is thrown in console: http://hastebin.com/zupovezuno.avrasm

To reproduce, attempt a command with any @ player selector in a command block. Usernames, however, work fine.

For example:

    /scoreboard players set tmad40blue shipParts 5

would work fine, but

    /scoreboard players set @a[r=20] shipParts 5

will error.

Thanks for all your help!

**Comment by wacossusca34** [comment] 2015-10-23 20:00
Issue is with the command sending, internal NPE when trying to work with selectors and not being able to determine self position. Either an issue with the wrapped sender, or the wrapper instance itself.

related line: https://github.com/wacossusca34/Consoles/blob/master/consoles-v1_8_R3/src/main/java/ca/jarcode/consoles/v1_8_R3/CommandBlockListenerWrapper.java#L154

(the corresponding v1_8_R2 module class will need to be fixed too)

This is really confusing for me because I have to shift through decompiled CB and NMS code (that has zero deobfuscation). From a bit of digging around, I think the issue is with the underlying `CommandBlockListenerAbstract` normally having public fields modified when mojang's code is doing magic and handling commands with target selectors.

I will push out a really tiny possible fix and update the latest snapshot shortly.

**Comment by wacossusca34** [comment] 2015-10-23 20:03
looks like returning null every time mojang's code wanted to get chunk coordinates from my wrapper was a bad idea. should be fixed now.

**Closed** 2015-10-23 20:03 UTC
Labels: bug

**Comment by wacossusca34** [comment] 2015-10-23 20:08
new snapshots should be deployed soon (wait ~5 mins), native code is also included in the snapshot for some library loading crap so hopefully that doesn't implode on anyone using the snapshots (not tested).
