### ISSUE TITLE
Could not pass event PlayerJoinEvent to ConsolesCore v1.2

### ISSUE THREAD

**Issue by Mabus13** [wacossusca34/Consoles#44] opened 2016-01-14 10:33 UTC
[11:04:38] [Server thread/WARN]: Tried to add entity Pig that already exists with UUID b17294a5-f345-4b64-b618-b50e01706f04
[11:08:27] [Thread-469/INFO]: UUID of player Ваня is 5870842a-1dba-3249-a2b2-02d99fca6afb
[11:08:27] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ConsolesCore v1.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Wrong protocol: LOGIN
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.wrapNetworkManager(PacketFunctions.java:252) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.registerOutListener(PacketFunctions.java:222) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.InternalPacketManager.registerMetadataPacketTranslator(InternalPacketManager.java:19) ~[?:?]
	at ca.jarcode.consoles.internal.ConsoleHandler.onPlayerJoin(ConsoleHandler.java:351) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	... 14 more
Caused by: java.lang.RuntimeException: Wrong protocol: LOGIN
	at ca.jarcode.consoles.v1_8_R3.NetworkManagerWrapper.wrap(NetworkManagerWrapper.java:79) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.wrapNetworkManager(PacketFunctions.java:247) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.registerOutListener(PacketFunctions.java:222) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.InternalPacketManager.registerMetadataPacketTranslator(InternalPacketManager.java:19) ~[?:?]
	at ca.jarcode.consoles.internal.ConsoleHandler.onPlayerJoin(ConsoleHandler.java:351) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-07c3001]
	... 14 more
[11:08:27] [Server thread/INFO]: [Essentials] Found new UUID for Ваня. Replacing 84e3d9fe-46f7-3ba5-b3ce-7c3aabebb760 with 5870842a-1dba-3249-a2b2-02d99fca6afb

**Comment by wacossusca34** [comment] 2016-01-20 21:18
I cannot reproduce this issue. Please give me a full plugin list and what spigot version you are running.

**Comment by Mabus13** [comment] 2016-01-20 21:52
Sorry for my annoying you. spigot (rev 566)
 Plugins (30): AsyncWorldEditInjector, craftinomicon, WorldEdit, Essentials, PacketListenerApi, ClearLag, AnimatedFrames, ReversCraft, ConsolesCore, ProtocolLib, NoCheatPlus, GravityGun, SkinsRestorer, AsyncWorldEdit, MyCraft, EssentialsChat, PermissionsEx, RandomTPItem, SkullTurret, GTADeath, Vault, GriefPrevention, EssentialsSpawn, TitleManager, AuthMe, ConsolesComputers, ResourcePackDownloader, HolographicDisplays, RPGHealthPlus, GPRealEstate

**Comment by Mabus13** [comment] 2016-01-20 21:53
Error not reproduce every time. But sometimes, i think on player joins.... =( I cant help with explain why it happened.

**Comment by wacossusca34** [comment] 2016-01-20 22:22
relevant event/line: https://github.com/wacossusca34/Consoles/blob/master/consoles-core/src/main/java/ca/jarcode/consoles/internal/ConsoleHandler.java#L350

the issue is that the join event is being fired before the protocol state is set to `PLAY`. Spigot and craftbukkit both do not have any bugs like this.

I am assuming it's `PacketListenerAPI`, you should not have that installed. ProtocolLib is the de-facto API for packet listening, any plugins that use `PacketListenerAPI` should be written to support ProtocolLib instead.

**Comment by Mabus13** [comment] 2016-01-20 22:28
AnimatedFrames use it api. I try switch off both plugins. And write here later - it resolve problem or not.

**Comment by wacossusca34** [comment] 2016-01-20 22:48
AnimatedFrames is not compatible with Consoles at all. ConsolesCore provides its own API for animated frames that is much faster, has per-player caches, and has various bug fixes and workarounds for client-side oddities. It is called ConsolesAPI and any developer can easily make use of it in their project.

AnimatedFrames, like every other plugin out there that attempts to try animating item frames, suffers from threading issues and bugs, and will encounter issues when players respawn/change worlds.

**Comment by Mabus13** [comment] 2016-01-21 03:07
Sorry man. Please open issue again because still same errror. Without that plugins:

[05:53:29] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ConsolesCore v1.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Wrong protocol: LOGIN
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.wrapNetworkManager(PacketFunctions.java:252) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.registerOutListener(PacketFunctions.java:222) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.InternalPacketManager.registerMetadataPacketTranslator(InternalPacketManager.java:19) ~[?:?]
	at ca.jarcode.consoles.internal.ConsoleHandler.onPlayerJoin(ConsoleHandler.java:351) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 14 more
Caused by: java.lang.RuntimeException: Wrong protocol: LOGIN
	at ca.jarcode.consoles.v1_8_R3.NetworkManagerWrapper.wrap(NetworkManagerWrapper.java:79) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.wrapNetworkManager(PacketFunctions.java:247) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.PacketFunctions.registerOutListener(PacketFunctions.java:222) ~[?:?]
	at ca.jarcode.consoles.v1_8_R3.InternalPacketManager.registerMetadataPacketTranslator(InternalPacketManager.java:19) ~[?:?]
	at ca.jarcode.consoles.internal.ConsoleHandler.onPlayerJoin(ConsoleHandler.java:351) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 14 more

Full log list plugins in end:
http://pastebin.com/HMttkPs5

**Comment by wacossusca34** [comment] 2016-01-21 08:20
Either way, those plugins should stay removed - they shouldn't have worked with Consoles at all anyway.

Quite frankly I'm not sure what's causing this for you - all the remaining plugins you have shouldn't interfere with the server's protocol state regarding a particular connection. You can try removing other plugins, (maybe client mods might be screwing with how protocol state packets are sent?).

Either there's still a conflict, or a bug in spigot. Version `git-Spigot-db6de12-18fbb24` (what you are running) is as of now, three versions behind. Update that first.

**Comment by Mabus13** [comment] 2016-01-21 15:41
Ok i try seek causes.

**Comment by Mabus13** [comment] 2016-01-30 19:57
Ehhh im very sorry im too newb and dumb in this forr seek causes of that problem. But problem still hapens like 15% chance of any player join event. Maybe you can say what i must do for help you found cause.

**Comment by wacossusca34** [comment] 2016-01-31 08:06
Happening '15%' of the time is not a reproduction case, I can't fix this issue unless I know how to cause it.

**Comment by Mabus13** [comment] 2016-01-31 08:19
Ye bro, you right... May i ask you list your regular plugins, for replace some my plugins by your analogs, maybe it help found cause....

**Comment by Mabus13** [comment] 2016-01-31 15:57
I have new log with server crash. Maybe it help with new info about cause...

http://hastebin.com/bahusatoza.coffee

**Comment by wacossusca34** [comment] 2016-01-31 17:06
It's the same log/issue. I need a way to cause it myself, stack traces help, but in this case it's the protocol state being incorrectly set while the player is joining. It does not happen on any server I have ever ran consoles on.

**Comment by Mabus13** [comment] 2016-01-31 17:53
How about i pack my server and give link for you download it? >_<

**Comment by Mabus13** [comment] 2016-01-31 21:19
New crash log:
http://hastebin.com/yohujuyoju.coffee

**Comment by wacossusca34** [comment] 2016-02-01 04:54
That crash log is not related to consoles in any way (from what I can tell). You need to tell me how to cause these issues, or I will close this.

**Comment by Mabus13** [comment] 2016-02-01 08:41
If i know how i not need help. =(

**Comment by Mabus13** [comment] 2016-02-01 22:56
May i ask you list your regular plugins, for replace some my plugins by your analogs, maybe it help found cause.... Also what regular use your server build version?

**Comment by wacossusca34** [comment] 2016-02-03 23:25
I keep my server build constantly updated, and I don't test with other plugins (nor do I host my own servers). If there's compatibility issues, I normally expect them to get reported.

**Comment by Mabus13** [comment] 2016-02-04 03:24
Ok may you try use your plugin with Auth Reloaded 3.5 ? Maybe here cause that error...

**Comment by wacossusca34** [comment] 2016-02-04 14:09
Authme is for offline servers, I'm not exactly willing to support offline/cracked servers. Part of your problem could be due to offline UUIDs.

Try running the server in online mode to see if the issue persists. If it doesn't, you have your cause.

**Comment by wacossusca34** [comment] 2016-02-04 14:13
Closing the issue since this presumably relates to offline servers (and the poster has been abusing this issue tracker).

**Closed by wacossusca34** 2016-02-04 14:13 UTC
Labels: invalid
