### ISSUE TITLE
Computers cause many map items to spawn when loading the chunk

### ISSUE THREAD

**Issue by coolyc3** [wacossusca34/Consoles#12] opened 2015-06-25 12:23 UTC
When loading an unloaded chunk with a computer it causes it to drop a lot of maps and item frames on the ground.
![2015-06-25_08 20 39](https://cloud.githubusercontent.com/assets/4468288/8354126/78052d68-1b13-11e5-91dc-6d95a27d4896.png)

**Comment by wacossusca34** [comment] 2015-06-25 22:01
wat

**Comment by vifino** [comment] 2015-06-25 22:02
wat

**Comment by wacossusca34** [comment] 2015-06-25 22:02
Can I have a plugin list and the version of Consoles that you are running? I fixed this bug a long time ago, so unless another plugin is interfering, this shouldn't happen.

**Comment by coolyc3** [comment] 2015-06-26 08:23
Here is the plugin list

Plugins (46): AsyncWorldEditInjector, CoreProtect, WorldEdit, AdminFun, ColoredSigns, ArcaneEnchants, Essentials, BarAPI, GroupManager, ClearLag, TuxTwoLib, CrackShot, WorldBorder, Votifier, ActionBarAPI, WorldGuard, Multiverse-Core, ProtocolLib, KitAdder, EssentialsProtect, Consoles, EssentialsChat, DeathMessages, BlocksHub, EssentialsAntiBuild, SQLibrary, Multiverse-Portals, ServerListPlus, Vault, GAListener, EssentialsSpawn, Lores, BlocksHub-CoreProtect, TitleManager, SimpleBroadcast, PurpleIRC, HolographicDisplays, SeparateWorldItems, Citizens, AsyncWorldEdit, Magic, Shopkeepers, Quests, AsyncWorldEdit-ActionBarAPI, CraftBook, MagicWorlds

**Comment by wacossusca34** [comment] 2015-06-26 20:57
I can't think why any of your current plugins would interfere with chunk unloading (ie. cancelling the event and then unloading the chunk manually, without going through bukkit). Do you get this all the time?

**Comment by coolyc3** [comment] 2015-06-26 22:13
I've tested and can confirm, every time the chunk is unloaded and reloaded this happens

**Comment by wacossusca34** [comment] 2015-06-26 22:14
weird. What's your server?

**Comment by coolyc3** [comment] 2015-06-27 04:06
Do you mean the IP?

On June 26, 2015, at 6:14 PM, Levi Webb <notifications@github.com> wrote:

weird. What's your server?

**Comment by vifino** [comment] 2015-06-27 16:01
No, I guess @wacossusca34 means what OS, hardware, things like that.

Would make more sense.

**Comment by coolyc3** [comment] 2015-06-29 02:27
Well im using McProHosting but i can paste their specs here
*"We utilize Dual Xeon E5-2620 Processors, DDR3 ECC RAM, Samsung SSDs, and 1 Gbps blended fiber connections on each box!"*

**Comment by wacossusca34** [comment] 2015-06-29 02:51
Actually, I did mean the IP so I could pop on and see the issue - although I won't be able to for a bit now.

**Comment by wacossusca34** [comment] 2015-10-20 05:35
I have accidentally reproduced this on testing, and after a bit of goofing around there are a few ways to get this:

- the server shuts down prematurely and plugins are not correctly disabled, but saved entities from chunks remain on file, which includes console frame entities. This could be fixed with an NMS hack to disable saving the entities to NBT in the region files, but it so rarely happens that I will not bother for now.

- a plugin conflicts with chunk unloading and causes consoles to not remove console entities as the chunks unload and save to NBT, causing the item frame entities to save to disk, and then load as vanilla floating maps.

any map entity that ends up getting saved to NBT in the world region file will not longer have any modded behaviour when loaded, so it results in the loads of dropped maps.

since one cause is an edge case that I can't be bothered to fix, and the other is an abstract issue with another plugin, I am closing this until I get more info.

**Closed** 2015-10-20 05:35 UTC
Labels: bug
