### ISSUE TITLE
ConsolesComputers/libcomputerimpl.so

### ISSUE THREAD

**Issue by BasixKOR** [wacossusca34/Consoles#42] opened 2015-12-15 11:19 UTC
[20:08:39] [Server thread/WARN]: java.nio.file.NoSuchFileException: /home/basix/문서/서버/Console/plugins/ConsolesComputers/libcomputerimpl.so
[20:08:39] [Server thread/WARN]: 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[20:08:39] [Server thread/WARN]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[20:08:39] [Server thread/WARN]: 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[20:08:39] [Server thread/WARN]: 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[20:08:39] [Server thread/WARN]: 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
[20:08:39] [Server thread/WARN]: 	at java.nio.file.Files.newOutputStream(Files.java:216)
[20:08:39] [Server thread/WARN]: 	at java.nio.file.Files.copy(Files.java:3016)
[20:08:39] [Server thread/WARN]: 	at ca.jarcode.consoles.computer.NativeLoader.extractLib(NativeLoader.java:97)
[20:08:39] [Server thread/WARN]: 	at ca.jarcode.consoles.computer.NativeLoader.loadAsJNILibrary(NativeLoader.java:66)
[20:08:39] [Server thread/WARN]: 	at ca.jarcode.consoles.Computers.onEnable(Computers.java:49)
[20:08:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:08:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:08:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:08:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:08:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:08:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199)
[20:08:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:08:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:08:39] [Server thread/ERROR]: Error occurred while enabling ConsolesComputers v1.2 (Is it up to date?)
java.lang.RuntimeException: Unsupported platform
	at ca.jarcode.consoles.computer.NativeLoader.extractLib(NativeLoader.java:104) ~[?:?]
	at ca.jarcode.consoles.computer.NativeLoader.loadAsJNILibrary(NativeLoader.java:66) ~[?:?]
	at ca.jarcode.consoles.Computers.onEnable(Computers.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [s.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [s.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [s.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [s.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [s.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [s.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by wacossusca34** [comment] 2015-12-16 04:39
Duplicate of #41, create the `ConsolesComputers` directory in your plugins folder and this will be fixed. It's a bug in the current release version.

Also, I can see you have unicode pathnames that extend past the single-byte character range - though this issue is unrelated, be sure to create a new one if you run into issues with character encoding. At the moment, character streaming is ASCII and UTF-8 streaming needs to be implemented/fixed.

**Closed by wacossusca34** 2015-12-16 04:39 UTC
