### ISSUE TITLE
Redstone indexes randomly change on server restart

### ISSUE THREAD

**Issue by tmad40blue** [wacossusca34/Consoles#35] opened 2015-11-06 18:16 UTC
Looks like the redstone indexes available through redstone() and redstoneInput() are resetting themselves - seemingly randomly - upon a server restart.

I've written a simple Lua program to test and reproduce: http://hastebin.com/hetagidubu.coffee

Ideally, this program would power the same redstone blocks for each index every time, but each computer has a habit of randomly changing its indexes! At the moment I'm having to go through and run this test on each computer I have in order to ensure proper redstone operation on every server restart.

**Comment by wacossusca34** [comment] 2015-11-07 00:40
The order of these indexes are calculated the same way:

    3 - 4 - 5
    0 - 1 - 2

These are the indexes behind a computer for each possible output. If an output doesn't exist, all the larger indexes get _shifted_ down, thus having a smaller maximum value. There is actually no way of mixing these values up, as they are checked in the order of the axis that the computer sits on (if that makes any sense).

Anyway, this is actually being caused by #36, since the output indexes are not being properly updated when the plugin loads.

**Closed by wacossusca34** 2015-11-07 00:40 UTC
